Repository kalispell-software-crafters/ai-image-analyzer, pull requests merged in 2023-03, with the labels that each got.

#10 Feature/add scaffolding
  README.md
  requirements.txt
  src/api/index.py
  src/classes/analysis_results.py
  src/classes/analyze_video_response.py
  src/classes/video_data.py
  src/services/image_analysis_service.py
  src/services/image_analysis_service_test.py
  src/services/video_service.py
  src/services/video_service_test.py
Labels: enhancement

#11 Adding CICD to Repository
  .flake8
  .github/workflows/code-linting.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  LICENSE.rst
  Makefile
  pyproject.toml
  requirements-deploy.txt
  requirements-dev.txt
  requirements.txt
  src/api/index.py
  src/classes/analysis_results.py
  src/classes/analyze_video_response.py
  src/classes/video_data.py
  src/services/image_analysis_service.py
  src/services/image_analysis_service_test.py
  src/services/video_service.py
  src/services/video_service_test.py
  template.envrc
Labels: cicd

#13 Adding scripts for local development via Docker
  .tmuxgo
  Makefile
  README.md
  docker/aliases.sh
  docker/docker-compose.yaml
  docker/image_analyzer.Dockerfile
  template.envrc
Labels: documentation, enhancement, refactoring

#14 Feature/add resource links
  Makefile
  README.md
Labels: documentation

#16 Feature/add tests to build
  .github/workflows/code-linting.yml
  Makefile
  README.md
Labels: unit tests

#19 Feature/add error handling
  src/api/index.py
  src/utils/default_variables.py
Labels: enhancement

#21 Add workflow status to readme.
  README.md
Labels: documentation

#22 Adding Pytube and OpenCV modules
  .isort.cfg
  docker/image_analyzer.Dockerfile
  requirements.txt
  src/classes/video_data.py
  src/services/prep_service.py
  src/utils/default_variables.py
Labels: enhancement, new module, refactoring
